### ISSUE TITLE
Requests from gateway not properly processed by backend servers

### ISSUE THREAD

**Issue by travisoneill** [travisoneill/algo-arena-v2#2]
Appears that data is not being sent correctly.  Servers logging no object.  

`TypeError: Cannot read property 'method' of undefined`

Flask server is refusing request with a 400: 

`problem with request: connect ECONNREFUSED 127.0.0.1:8001`

**Comment by DaC00P** [comment]
server not live, tested, OR QA-d yet. Just a prototype (that's not functional yet). Need to finish implementing promise based HTTP request system.
